# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

compiler: gcc

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='http://ssb.stsci.edu/astroconda'
        - CONDA_DEPENDENCIES='pytest sphinx'
        - PIP_DEPENDENCIES=''
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - EVENT_TYPE='push pull_request'

    matrix:
        - SETUP_CMD='install'
        - SETUP_CMD='test'
#        - PYTHON_VERSION=2.7 SETUP_CMD='test'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        # build sphinx documentation with warnings
        - os: linux
          env: SETUP_CMD='build_sphinx'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES
               PIP_DEPENDENCIES='sphinx_rtd_theme stsci_rtd_theme sphinx-automodapi'

        # PEP8 check with flake8 (only once, i.e. "os: linux")
        - os: linux
          env: MAIN_CMD='flake8 --count'
               SETUP_CMD='pysiaf' TEST_CMD='flake8 --version'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES

    allow_failures:
        # PEP8 will fail for numerous reasons. Ignore it.
        - env: MAIN_CMD='flake8 --count'
               SETUP_CMD='pysiaf' TEST_CMD='flake8 --version'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - $MAIN_CMD $SETUP_CMD

deploy:
  provider: pypi
  user: johannes-sahlmann
  password:
    secure: db0mdszYWwzBeCsfg3gsWU0/eR4n30twX6UOoHD5wt8H1HadiPHaoJ4lHISTstaWu35IPfbaDcTJuqm67H8GfBOpVRMBxyfHRHoS86aXlAFT6hWjchRTDKLW9+igbCkGbcd9oxflXM27nIOz2kOwimdglXRq5VUH6kx/PaZ/rRbyX/wBO7BiUQo4LHBqz0MTR3TFnPi0TbamlbQw7jQBTom3TTStuSOzdlGYDvfSi5rN9hyBHcw6IV/P2x2cNGQy6eQFHBuRng0/UGk4GobWtX12DOviQkIHiNQBuNsW3Vw7bFcyqs2kUONXtiAugsFLXoSARyOgePmgdl9vQhZK5jpGH7ejE2FuvjwcuJvq4Tn10yI+nfVXz2qYN5PhWkUnjSRaCFDWBPrORlfR7fWkZNTUONiiDmKRWKbFUJlSUh0mV4+E/8zOoy5nfhEwgbe5rDDPWNNXmntT3I182+ApaKaQeo9JfEZi/7MOdHLupiwN4L5ukJQC5J+q2jzfHDV6UWiybE+eVX175HuVHW+vo55r9U7RWR2vp2NmJ7yd4VKksmkH/mfa+S6mEaIgV0esxQ+VF7gmdPo3LoC3ovKrCRxcTndxrbo8rXoa0sd3fLfEB2r/z2Pc2eWtHq7wi4UcIUIQydqGZOh6U/ic4VoBNWEwyTQjmxQ3QuZ1SSAzjWk=
  on:
#    tags: true
    branch: master